#!/bin/bash
command -v ncrack >/dev/null 2>&1 || { 
    echo "*********";
    echo -e >&2 " ncrack not installed.";
    echo "*********";
    echo "sudo apt-get install ncrack" ;
    echo "--------------------"
    exit 1; 
}

rm nohup.out 2>/dev/null
read -p "Would you like to check your network for vulnerable devices (Y/n):"  ans
case $ans in
	Y)
		./whiteWorm.sh ;#First script to find vulnerable IPs
		ncrack -oN output.txt -U username.txt -P password.txt -iL ip_vulnerable.txt -p 22;
		cat output.txt | grep "ssh:" | cut -d " " -f1,4,5 | tr -d "'" > crackedCreds.txt;
		[ -s crackedCreds.txt ]
		if [ $? == 0 ]
		then
			./secureCreds.sh crackedCreds.txt #Second script to change passwords
		else
			echo "You have no vulnerable devices"
		fi
		;;
	n)
		echo "Have a good day!"
		;;
esac

# clean up
rm crackedCreds.txt 2>/dev/null
rm ip_vulnerable.txt 2>/dev/null

#run honey pot here
#add /usr/bin/python3 to top of script
#chmod +x 
nohup ./test.py &
rm nohup.out 2>/dev/null





